# Generated by Django 4.0.6 on 2023-08-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clint_sys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(default='5bb525c3', editable=False, max_length=30, unique=True)),
                ('date_join', models.DateField(auto_now_add=True)),
                ('date_expired', models.DateField()),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('subType', models.CharField(choices=[('شهري', 'شهري'), ('نصف سنوي', 'نصف سنوي'), ('سنوي', 'سنوي'), ('ربع سنوي', 'ربع سنوي'), ('اخرئ', 'اخرئ')], max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='Compny name')),
                ('version', models.CharField(choices=[('تجريبي', 'تجريبي'), ('رسمي', 'رسمي')], max_length=20)),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='version status')),
            ],
        ),
    ]
