# Generated by Django 4.0.6 on 2023-08-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clint_sys',
            name='code',
            field=models.CharField(default='aecbea62', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='clint_sys',
            name='date_expired',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clint_sys',
            name='date_join',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
